version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:ubuntu
    steps:
      - checkout
      - run: echo "Hello World"
      - run: sudo apt install -y m4
      - run: opam install -y  --deps-only .
      - run: dune build
